version: '3'
services:

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment: 
      POSTGRES_DB: youtube
      POSTGRES_USER: saurabh
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - 5432:5432

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  dashboard-service:
    container_name: dashboard-service
    build:
      dockerfile: Dockerfile.dev
      context: ./dashboard-service
    volumes:
      - /app/node_modules
      - ./dashboard-service:/app
    environment:
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: '9200'
    depends_on: 
      - elasticsearch

  search-service:
    container_name: search-service
    environment:
      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: '9200'
    build:
      dockerfile: Dockerfile.dev
      context: ./search-service
    volumes:
      - /app/node_modules
      - ./search-service:/app

  update-datastore-service:
    container_name: update-datastore-service
    build: 
      dockerfile: Dockerfile.dev
      context: ./update-datastore-service
    environment:
        PGUSER: saurabh
        PGHOST: postgres
        PGDATABASE: youtube
        PGPASSWORD: super_secret_password
        PGPORT: 5432
        SEARCH_TERM: cricket
        # API Keys Encoded
        GOOGLE_API_KEYS: >
          QUl6YVN5QjlUUDFpbV91Nk5KZlJ3a2VZeXZSbHVqa2ptQ2xCV0VJ
          QUl6YVN5RFJBb0FMSkJaMlB2TWxzMWFHTlJpNkhFa2cwLVF3SlVr
          QUl6YVN5RHRUREwwMEhOQks2TVFGLTU3eThqS1NaZjk5NGIzWC0w
        SEED_COUNT: '1000'
        UPDATE_FREQUENCY: '1000000000000000'
    volumes:
        - /app/node_modules
        - ./update-datastore-service:/app

  client:
    container_name: client
    build:
        dockerfile: Dockerfile
        context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    volumes:
        - elastic-data:/usr/share/elasticsearch/data
    environment:
        - discovery.type=single-node
    ports:
        - 9300:9300
        - 9200:9200

  kibana:
    image: kibana:7.14.0
    environment: 
        SERVER_NAME: kibana
        ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
        - 5601:5601

   # logstash
  logstash: 
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: logstash
    volumes: 
         - ./logstash/pusher.conf:/usr/share/logstash/config/pusher.conf:ro
         - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
         - ./logstash/jdbc/postgresql-42.2.6.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.6.jar:ro
    ports:
        - '5044:5044'
        - '9600:9600'
    command: bash -c "/usr/share/logstash/bin/logstash-plugin install logstash-input-jdbc && logstash -f /usr/share/logstash/config/pusher.conf"
    depends_on:
        - elasticsearch

volumes:
    elastic-data:
