version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  results-service:
    container_name: results-service
    build:
      dockerfile: Dockerfile.dev
      context: ./results-service
    volumes:
      - /app/node_modules
      - ./results-service:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  search-service:
    container_name: search-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./search-service
    volumes:
      - /app/node_modules
      - ./search-service:/app
  client:
    container_name: client
    build:
        dockerfile: Dockerfile.dev
        context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app
